import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import dotenv from "dotenv";
import User from "./models/User.js";
import Video from "./models/Video.js";

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/chsetube";

// Helper for extracting YouTube ID
function getYTId(url) {
  if (!url) return "";
  const match = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/|live\/)|youtu\.be\/)([^&\n?#]+)/);
  return match ? match[1] : "";
}

export const INITIAL_VIDEOS = [
  // ==================== CLASS 12 SCIENCE ====================
  // PHYSICS
  {
    chapterId: "ph12_1_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_1",
    unitName: "Unit I: Electrostatics",
    title: "Electric Charges and Fields",
    desc: "Coulomb's Law, Electric dipole, Gauss's Theorem and applications.",
    videoUrl: "https://youtu.be/P_r3N9pC5p4",
    order: 1,
  },
  {
    chapterId: "ph12_1_2",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_1",
    unitName: "Unit I: Electrostatics",
    title: "Electrostatic Potential and Capacitance",
    desc: "Electric potential, Equipotential surfaces, Capacitors in series and parallel.",
    videoUrl: "https://youtu.be/6_Z_W9_b2-g",
    order: 2,
  },
  {
    chapterId: "ph12_2_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_2",
    unitName: "Unit II: Current Electricity",
    title: "Current Electricity",
    desc: "Ohm's Law, Drift velocity, Kirchhoff's Laws, Wheatstone Bridge, Potentiometer.",
    videoUrl: "https://youtu.be/7oZ_m9_c3-h",
    order: 3,
  },
  {
    chapterId: "ph12_3_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_3",
    unitName: "Unit III: Magnetic Effects of Current & Magnetism",
    title: "Moving Charges and Magnetism",
    desc: "Biot-Savart law, Ampere's circuital law, Force on current carrying conductor.",
    videoUrl: "https://youtu.be/8pZ_n0_d4-j",
    order: 4,
  },
  {
    chapterId: "ph12_3_2",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_3",
    unitName: "Unit III: Magnetic Effects of Current & Magnetism",
    title: "Magnetism and Matter",
    desc: "Bar magnet, Magnetic dipole moment, Earth's magnetism, Magnetic materials.",
    videoUrl: "https://youtu.be/9qZ_p1_e5-k",
    order: 5,
  },
  {
    chapterId: "ph12_4_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_4",
    unitName: "Unit IV: Electromagnetic Induction & AC",
    title: "Electromagnetic Induction",
    desc: "Faraday's laws, Lenz's Law, Eddy currents, Self and mutual inductance.",
    videoUrl: "https://youtu.be/0rZ_q2_f6-l",
    order: 6,
  },
  {
    chapterId: "ph12_4_2",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_4",
    unitName: "Unit IV: Electromagnetic Induction & AC",
    title: "Alternating Current",
    desc: "Peak and RMS value, LCR series circuit, Resonance, Power in AC, Transformers.",
    videoUrl: "https://youtu.be/1sZ_r3_g7-m",
    order: 7,
  },
  {
    chapterId: "ph12_5_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_5",
    unitName: "Unit V: Optics",
    title: "Ray Optics and Optical Instruments",
    desc: "Reflection, Refraction, Total internal reflection, Lens formula, Microscope, Telescope.",
    videoUrl: "https://youtu.be/2tZ_s4_h8-n",
    order: 8,
  },
  {
    chapterId: "ph12_5_2",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_5",
    unitName: "Unit V: Optics",
    title: "Wave Optics",
    desc: "Wavefront, Huygens principle, Young's double slit experiment, Diffraction, Polarization.",
    videoUrl: "https://youtu.be/3uZ_t5_i9-o",
    order: 9,
  },
  {
    chapterId: "ph12_6_1",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_6",
    unitName: "Unit VI: Modern Physics & Semiconductors",
    title: "Dual Nature of Radiation and Matter",
    desc: "Photoelectric effect, Einstein's equation, de-Broglie hypothesis.",
    videoUrl: "https://youtu.be/4vZ_u6_j0-p",
    order: 10,
  },
  {
    chapterId: "ph12_6_2",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_6",
    unitName: "Unit VI: Modern Physics & Semiconductors",
    title: "Atoms and Nuclei",
    desc: "Rutherford & Bohr atomic models, Nuclear binding energy, Radioactivity, Nuclear fission.",
    videoUrl: "https://youtu.be/5wZ_v7_k1-q",
    order: 11,
  },
  {
    chapterId: "ph12_6_3",
    stream: "Science",
    class: "12",
    subject: "Physics",
    unitId: "unit_6",
    unitName: "Unit VI: Modern Physics & Semiconductors",
    title: "Semiconductor Electronics",
    desc: "Energy bands, p-n junction diode, Rectifiers, Zener diode, Logic gates.",
    videoUrl: "https://youtu.be/6xZ_w8_l2-r",
    order: 12,
  },

  // CHEMISTRY
  {
    chapterId: "ch12_1_1",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_1",
    unitName: "Unit I: Physical Chemistry",
    title: "Solutions",
    desc: "Types of solutions, Raoult's law, Colligative properties, van't Hoff factor.",
    videoUrl: "https://youtu.be/r6Z_w8_b1-a",
    order: 1,
  },
  {
    chapterId: "ch12_1_2",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_1",
    unitName: "Unit I: Physical Chemistry",
    title: "Electrochemistry",
    desc: "Galvanic cells, Nernst equation, Conductance, Kohlrausch's law, Electrolysis.",
    videoUrl: "https://youtu.be/s7Z_x9_c2-b",
    order: 2,
  },
  {
    chapterId: "ch12_1_3",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_1",
    unitName: "Unit I: Physical Chemistry",
    title: "Chemical Kinetics",
    desc: "Rate of reaction, Order and molecularity, Integrated rate equations, Arrhenius equation.",
    videoUrl: "https://youtu.be/t8Z_y0_d3-c",
    order: 3,
  },
  {
    chapterId: "ch12_2_1",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_2",
    unitName: "Unit II: Inorganic Chemistry",
    title: "d and f Block Elements",
    desc: "Transition metals, Lanthanoids, Actinoids, K2Cr2O7 and KMnO4.",
    videoUrl: "https://youtu.be/u9Z_z1_e4-d",
    order: 4,
  },
  {
    chapterId: "ch12_2_2",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_2",
    unitName: "Unit II: Inorganic Chemistry",
    title: "Coordination Compounds",
    desc: "Werner's theory, IUPAC nomenclature, Valence bond theory, Crystal field theory.",
    videoUrl: "https://youtu.be/v0Z_a2_f5-e",
    order: 5,
  },
  {
    chapterId: "ch12_3_1",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_3",
    unitName: "Unit III: Organic Chemistry",
    title: "Haloalkanes and Haloarenes",
    desc: "SN1 and SN2 mechanisms, Optical rotation, Polyhalogen compounds.",
    videoUrl: "https://youtu.be/w1Z_b3_g6-f",
    order: 6,
  },
  {
    chapterId: "ch12_3_2",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_3",
    unitName: "Unit III: Organic Chemistry",
    title: "Alcohols, Phenols and Ethers",
    desc: "Preparation, Acidic nature, Reimer-Tiemann reaction, Kolbe's reaction, Williamson synthesis.",
    videoUrl: "https://youtu.be/x2Z_c4_h7-g",
    order: 7,
  },
  {
    chapterId: "ch12_3_3",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_3",
    unitName: "Unit III: Organic Chemistry",
    title: "Aldehydes, Ketones and Carboxylic Acids",
    desc: "Nucleophilic addition, Aldol condensation, Cannizzaro reaction, Acidity of carboxylic acids.",
    videoUrl: "https://youtu.be/y3Z_d5_i8-h",
    order: 8,
  },
  {
    chapterId: "ch12_3_4",
    stream: "Science",
    class: "12",
    subject: "Chemistry",
    unitId: "unit_3",
    unitName: "Unit III: Organic Chemistry",
    title: "Amines & Biomolecules",
    desc: "Basicity of amines, Diazonium salts, Carbohydrates, Proteins, Nucleic acids.",
    videoUrl: "https://youtu.be/z4Z_e6_j9-i",
    order: 9,
  },

  // MATHEMATICS
  {
    chapterId: "ma12_1_1",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_1",
    unitName: "Unit I: Relations and Functions",
    title: "Relations and Functions",
    desc: "Types of relations, Equivalence relations, One-one and onto functions, Composite functions.",
    videoUrl: "https://youtu.be/a5Z_f7_k0-j",
    order: 1,
  },
  {
    chapterId: "ma12_1_2",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_1",
    unitName: "Unit I: Relations and Functions",
    title: "Inverse Trigonometric Functions",
    desc: "Principal value branch, Domain, Range, and key algebraic properties.",
    videoUrl: "https://youtu.be/b6Z_g8_l1-k",
    order: 2,
  },
  {
    chapterId: "ma12_2_1",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_2",
    unitName: "Unit II: Algebra (Matrices & Determinants)",
    title: "Matrices",
    desc: "Matrix operations, Symmetric and skew-symmetric, Invertible matrices.",
    videoUrl: "https://youtu.be/c7Z_h9_m2-l",
    order: 3,
  },
  {
    chapterId: "ma12_2_2",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_2",
    unitName: "Unit II: Algebra (Matrices & Determinants)",
    title: "Determinants",
    desc: "Properties of determinants, Area of triangles, Adjoint and inverse, Cramer's rule.",
    videoUrl: "https://youtu.be/d8Z_i0_n3-m",
    order: 4,
  },
  {
    chapterId: "ma12_3_1",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_3",
    unitName: "Unit III: Differential Calculus",
    title: "Continuity and Differentiability",
    desc: "Continuity, Chain rule, Implicit functions, Exponential & Logarithmic differentiation.",
    videoUrl: "https://youtu.be/e9Z_j1_o4-n",
    order: 5,
  },
  {
    chapterId: "ma12_3_2",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_3",
    unitName: "Unit III: Differential Calculus",
    title: "Applications of Derivatives",
    desc: "Rate of change, Tangents and normals, Maxima and minima, Increasing/decreasing functions.",
    videoUrl: "https://youtu.be/f0Z_k2_p5-o",
    order: 6,
  },
  {
    chapterId: "ma12_4_1",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_4",
    unitName: "Unit IV: Integral Calculus",
    title: "Integrals",
    desc: "Indefinite & definite integrals, Integration by substitution, Parts, Partial fractions.",
    videoUrl: "https://youtu.be/g1Z_l3_q6-p",
    order: 7,
  },
  {
    chapterId: "ma12_4_2",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_4",
    unitName: "Unit IV: Integral Calculus",
    title: "Applications of Integrals & Differential Equations",
    desc: "Area under curves, Order & degree, Variable separable method, Linear differential equations.",
    videoUrl: "https://youtu.be/h2Z_m4_r7-q",
    order: 8,
  },
  {
    chapterId: "ma12_5_1",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_5",
    unitName: "Unit V: Vectors, 3D & Probability",
    title: "Vectors and 3-Dimensional Geometry",
    desc: "Dot and cross products, Direction cosines, Line and plane equations.",
    videoUrl: "https://youtu.be/i3Z_n5_s8-r",
    order: 9,
  },
  {
    chapterId: "ma12_5_2",
    stream: "Science",
    class: "12",
    subject: "Mathematics",
    unitId: "unit_5",
    unitName: "Unit V: Vectors, 3D & Probability",
    title: "Linear Programming and Probability",
    desc: "Graphical LPP, Conditional probability, Bayes' Theorem, Bernoulli trials.",
    videoUrl: "https://youtu.be/j4Z_o6_t9-s",
    order: 10,
  },

  // BIOLOGY (OFFICIAL 5 UNITS PER CHSE SYLLABUS DIRECTIVE)
  {
    chapterId: "bi12_1_1",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_1",
    unitName: "Unit I: Reproduction",
    title: "Sexual Reproduction in Flowering Plants",
    desc: "Flower structure, Development of male and female gametophytes, Pollination, Double fertilisation, Seed development.",
    videoUrl: "https://youtu.be/6eZ_w8_l2-r",
    order: 1,
  },
  {
    chapterId: "bi12_1_2",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_1",
    unitName: "Unit I: Reproduction",
    title: "Human Reproduction & Reproductive Health",
    desc: "Male and female reproductive systems, Spermatogenesis, Oogenesis, Menstrual cycle, IVF, Contraception, STDs.",
    videoUrl: "https://youtu.be/7fZ_x9_m3-s",
    order: 2,
  },
  {
    chapterId: "bi12_2_1",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_2",
    unitName: "Unit II: Genetics and Evolution",
    title: "Principles of Inheritance and Variation",
    desc: "Mendelian inheritance, Deviations from Mendelism, Incomplete dominance, Chromosome theory, Sex determination, Genetic disorders.",
    videoUrl: "https://youtu.be/8gZ_y0_n4-t",
    order: 3,
  },
  {
    chapterId: "bi12_2_2",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_2",
    unitName: "Unit II: Genetics and Evolution",
    title: "Molecular Basis of Inheritance & Evolution",
    desc: "DNA structure, Replication, Transcription, Genetic code, Translation, Gene regulation, Human Genome Project, Darwinian selection.",
    videoUrl: "https://youtu.be/9hZ_z1_o5-u",
    order: 4,
  },
  {
    chapterId: "bi12_3_1",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_3",
    unitName: "Unit III: Biology and Human Welfare",
    title: "Human Health and Diseases",
    desc: "Pathogens, Parasites causing human diseases (Malaria, Typhoid, Pneumonia, Filariasis), Immunology, Vaccines, Cancer, HIV/AIDS.",
    videoUrl: "https://youtu.be/0iZ_a2_p6-v",
    order: 5,
  },
  {
    chapterId: "bi12_3_2",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_3",
    unitName: "Unit III: Biology and Human Welfare",
    title: "Microbes in Human Welfare",
    desc: "Microbes in household food processing, Industrial production, Sewage treatment, Biogas, Biocontrol agents, Biofertilisers.",
    videoUrl: "https://youtu.be/1jZ_b3_q7-w",
    order: 6,
  },
  {
    chapterId: "bi12_4_1",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_4",
    unitName: "Unit IV: Biotechnology and its Applications",
    title: "Biotechnology: Principles and Processes",
    desc: "Genetic engineering (Recombinant DNA technology), Restriction enzymes, Cloning vectors, PCR, Downstream processing.",
    videoUrl: "https://youtu.be/2kZ_c4_r8-x",
    order: 7,
  },
  {
    chapterId: "bi12_4_2",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_4",
    unitName: "Unit IV: Biotechnology and its Applications",
    title: "Applications of Biotechnology in Health and Agriculture",
    desc: "Genetically Modified Organisms (Bt cotton), Human insulin and vaccine production, Gene therapy, Transgenic animals, Biosafety.",
    videoUrl: "https://youtu.be/3lZ_d5_s9-y",
    order: 8,
  },
  {
    chapterId: "bi12_5_1",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_5",
    unitName: "Unit V: Ecology and Environment",
    title: "Organisms and Populations",
    desc: "Habitat and niche, Population attributes, Growth curves, Population interactions (Mutualism, Competition, Predation, Parasitism).",
    videoUrl: "https://youtu.be/4mZ_e6_t0-z",
    order: 9,
  },
  {
    chapterId: "bi12_5_2",
    stream: "Science",
    class: "12",
    subject: "Biology",
    unitId: "unit_5",
    unitName: "Unit V: Ecology and Environment",
    title: "Ecosystem & Biodiversity Conservation",
    desc: "Ecosystem structure, Productivity, Decomposition, Energy flow, Ecological pyramids, Patterns of biodiversity, In-situ and Ex-situ conservation.",
    videoUrl: "https://youtu.be/5nZ_f7_u1-a",
    order: 10,
  },

  // ENGLISH (FROM PW LIVE CLASS 12 DIRECTIVE)
  {
    chapterId: "en12_1_1",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_1",
    unitName: "Unit I: Prose",
    title: "The Greatest Olympic Prize",
    desc: "Jesse Owens' heartwarming story of true sportsmanship and friendship in Berlin Olympics.",
    videoUrl: "https://youtu.be/g6Z_h8_v2-b",
    order: 1,
  },
  {
    chapterId: "en12_1_2",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_1",
    unitName: "Unit I: Prose",
    title: "On Examinations",
    desc: "Winston Churchill's humorous perspective on academic assessments and examinations.",
    videoUrl: "https://youtu.be/h7Z_i9_w3-c",
    order: 2,
  },
  {
    chapterId: "en12_1_3",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_1",
    unitName: "Unit I: Prose",
    title: "The Portrait of a Lady",
    desc: "Khushwant Singh's tender biographical portrait of his grandmother and emotional bonds.",
    videoUrl: "https://youtu.be/i8Z_j0_x4-d",
    order: 3,
  },
  {
    chapterId: "en12_1_4",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_1",
    unitName: "Unit I: Prose",
    title: "The Magic of Teamwork",
    desc: "Sam Pitroda's insightful essay on collaboration, institutional building, and division of labor.",
    videoUrl: "https://youtu.be/j9Z_k1_y5-e",
    order: 4,
  },
  {
    chapterId: "en12_2_1",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_2",
    unitName: "Unit II: Poetry",
    title: "Daffodils & The Ballad of Father Gilligan",
    desc: "William Wordsworth's nature lyric and W.B. Yeats' spiritual ballad of devotion.",
    videoUrl: "https://youtu.be/k0Z_l2_z6-f",
    order: 5,
  },
  {
    chapterId: "en12_2_2",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_2",
    unitName: "Unit II: Poetry",
    title: "Psalm of Life & Television & Money Madness",
    desc: "Longfellow's inspiring philosophy, Roald Dahl's satire on screens, and D.H. Lawrence's critique of greed.",
    videoUrl: "https://youtu.be/l1Z_m3_a7-g",
    order: 6,
  },
  {
    chapterId: "en12_3_1",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_3",
    unitName: "Unit III: Non-Detailed Study",
    title: "The Doctor's Word & The Nightingale and the Rose",
    desc: "R.K. Narayan's classic story of Dr. Raman and Oscar Wilde's timeless romantic fable.",
    videoUrl: "https://youtu.be/m2Z_n4_b8-h",
    order: 7,
  },
  {
    chapterId: "en12_3_2",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_3",
    unitName: "Unit III: Non-Detailed Study",
    title: "Mystery of a Missing Cap & The Monkey's Paw & Stay Hungry",
    desc: "Manoj Das' political satire, W.W. Jacobs' suspense classic, and Steve Jobs' Stanford address.",
    videoUrl: "https://youtu.be/n3Z_o5_c9-i",
    order: 8,
  },
  {
    chapterId: "en12_4_1",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_4",
    unitName: "Unit IV: Writing Skills & Grammar",
    title: "Data Interpretation, Report Writing & Note Making",
    desc: "Interpreting graphs and charts, professional journalistic reports, systematic note-taking.",
    videoUrl: "https://youtu.be/o4Z_p6_d0-j",
    order: 9,
  },
  {
    chapterId: "en12_4_2",
    stream: "Science",
    class: "12",
    subject: "English",
    unitId: "unit_4",
    unitName: "Unit IV: Writing Skills & Grammar",
    title: "Advanced Grammar: Tenses, Modals, Voice & Speech",
    desc: "Mastery over tenses, active/passive voice, direct/indirect narration, conditional clauses.",
    videoUrl: "https://youtu.be/p5Z_q7_e1-k",
    order: 10,
  },

  // ODIA MIL (FROM PW LIVE CLASS 12 DIRECTIVE)
  {
    chapterId: "od12_1_1",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_1",
    unitName: "Unit I: ଗଦ୍ୟ (Prose)",
    title: "ଇତିହାସ ଓ ପୁଷ୍ପପୁରରେ ବର୍ଷାବରଣ",
    desc: "ବିଶ୍ୱନାଥ କରଙ୍କ 'ଇତିହାସ' ପ୍ରବନ୍ଧ ଓ କୃଷ୍ଣଚନ୍ଦ୍ର ପାଣିଗ୍ରାହୀଙ୍କ 'ପୁଷ୍ପପୁରରେ ବର୍ଷାବରଣ'ର ଭାବାର୍ଥ।",
    videoUrl: "https://youtu.be/q6Z_r8_f2-l",
    order: 1,
  },
  {
    chapterId: "od12_1_2",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_1",
    unitName: "Unit I: ଗଦ୍ୟ (Prose)",
    title: "ତିନି ତୁଣ୍ଡରେ ଓ ସ୍ୱାଧୀନ ଦେଶରେ ଶିକ୍ଷାଚିନ୍ତା",
    desc: "ଭୁବନେଶ୍ୱର ବେହେରାଙ୍କ 'ତିନି ତୁଣ୍ଡରେ' ଏବଂ ଗୋଲକ ବିହାରୀ ଧଳଙ୍କ ଶିକ୍ଷା ସଂସ୍କାର ବିଷୟକ ଆଲେଖ୍ୟ।",
    videoUrl: "https://youtu.be/r7Z_s9_g3-m",
    order: 2,
  },
  {
    chapterId: "od12_2_1",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_2",
    unitName: "Unit II: ପଦ୍ୟ (Poetry)",
    title: "ବଡ଼ପଣ ଓ ତପସ୍ୱିନୀର ପତ୍ର",
    desc: "କବିବର ରାଧାନାଥ ରାୟଙ୍କ 'ବଡ଼ପଣ' ଏବଂ ସ୍ୱଭାବକବି ଗଙ୍ଗାଧର ମେହେରଙ୍କ 'ତପସ୍ୱିନୀର ପତ୍ର'।",
    videoUrl: "https://youtu.be/s8Z_t0_h4-n",
    order: 3,
  },
  {
    chapterId: "od12_2_2",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_2",
    unitName: "Unit II: ପଦ୍ୟ (Poetry)",
    title: "ବନ୍ଦୀର ବିରହ ବ୍ୟଥା, ପିଙ୍ଗଳାର ଅଭିସାର ଓ ବାର୍ତ୍ତା",
    desc: "ଗୋପବନ୍ଧୁ ଦାସ, ରାଧାମୋହନ ଗଡ଼ନାୟକ ଓ ସଚ୍ଚି ରାଉତରାୟଙ୍କ କାଳଜୟୀ କବିତା।",
    videoUrl: "https://youtu.be/t9Z_u1_i5-o",
    order: 4,
  },
  {
    chapterId: "od12_3_1",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_3",
    unitName: "Unit III: ଗଳ୍ପ (Short Stories)",
    title: "ସଭ୍ୟ ଜମିଦାର ଓ ପତାକା ଉତ୍ତୋଳନ",
    desc: "ବ୍ୟାସକବି ଫକୀର ମୋହନ ସେନାପତିଙ୍କ 'ସଭ୍ୟ ଜମିଦାର' ଏବଂ ସୁରେନ୍ଦ୍ର ମହାନ୍ତିଙ୍କ 'ପତାକା ଉତ୍ତୋଳନ'।",
    videoUrl: "https://youtu.be/u0Z_v2_j6-p",
    order: 5,
  },
  {
    chapterId: "od12_3_2",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_3",
    unitName: "Unit III: ଗଳ୍ପ (Short Stories)",
    title: "ରୂପ ନାରାୟଣ ସାହା ଓ ଆକାଶ କଇଁଛ",
    desc: "ଅଖିଳ ମୋହନ ପଟ୍ଟନାୟକଙ୍କ 'ରୂପ ନାରାୟଣ ସାହା' ଏବଂ ମନୋଜ ଦାସଙ୍କ 'ଆକାଶ କଇଁଛ'।",
    videoUrl: "https://youtu.be/v1Z_w3_k7-q",
    order: 6,
  },
  {
    chapterId: "od12_4_1",
    stream: "Science",
    class: "12",
    subject: "Odia",
    unitId: "unit_4",
    unitName: "Unit IV: ବୋଧଜ୍ଞାନ, ପ୍ରବନ୍ଧ ଓ ବ୍ୟାକରଣ",
    title: "ବୋଧଜ୍ଞାନ ପରୀକ୍ଷଣ, ସର୍ଜନାତ୍ମକ ରଚନା ଓ ବ୍ୟାକରଣ",
    desc: "ଅବବୋଧ ପରୀକ୍ଷଣ, ଦରଖାସ୍ତ ଲିଖନ, ପ୍ରବନ୍ଧ ରଚନା, ରୂଢ଼ି ଓ ଲୋକବାଣୀ, ଶବ୍ଦଶୁଦ୍ଧି।",
    videoUrl: "https://youtu.be/w2Z_x4_l8-r",
    order: 7,
  },

  // IT (FROM PW LIVE CLASS 12 DIRECTIVE)
  {
    chapterId: "it12_1_1",
    stream: "Science",
    class: "12",
    subject: "IT",
    unitId: "unit_1",
    unitName: "Unit I: Computer Networking & Web",
    title: "Computer Networking & Internet Applications",
    desc: "Network topologies, Transmission media, OSI reference model, TCP/IP, DNS, Web browsers.",
    videoUrl: "https://youtu.be/x3Z_y5_m9-s",
    order: 1,
  },
  {
    chapterId: "it12_1_2",
    stream: "Science",
    class: "12",
    subject: "IT",
    unitId: "unit_1",
    unitName: "Unit I: Computer Networking & Web",
    title: "Network Security & HTML Web Pages",
    desc: "Firewalls, Malware, Cryptography, HTML structure, Form inputs, CSS styling basics.",
    videoUrl: "https://youtu.be/y4Z_z6_n0-t",
    order: 2,
  },
  {
    chapterId: "it12_2_1",
    stream: "Science",
    class: "12",
    subject: "IT",
    unitId: "unit_2",
    unitName: "Unit II: Database & Programming",
    title: "Programming Fundamentals & Database Concepts",
    desc: "Data types, Control flow, Functions, Relational data model, Primary and foreign keys.",
    videoUrl: "https://youtu.be/z5Z_a7_o1-u",
    order: 3,
  },
  {
    chapterId: "it12_2_2",
    stream: "Science",
    class: "12",
    subject: "IT",
    unitId: "unit_2",
    unitName: "Unit II: Database & Programming",
    title: "MySQL Queries & E-Business Systems",
    desc: "DDL and DML commands, SELECT, WHERE, GROUP BY, E-Commerce models, Digital payment gateways.",
    videoUrl: "https://youtu.be/a6Z_b8_p2-v",
    order: 4,
  },
];

async function seedDatabase() {
  try {
    console.log("Connecting to MongoDB for seeding...");
    await mongoose.connect(MONGODB_URI);
    console.log("Connected successfully.");

    // Create Admin User only if environment variables are provided
    if (process.env.ADMIN_EMAIL && process.env.ADMIN_PASSWORD) {
      const adminEmail = process.env.ADMIN_EMAIL.toLowerCase().trim();
      const existingAdmin = await User.findOne({ email: adminEmail });
      if (!existingAdmin) {
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(process.env.ADMIN_PASSWORD, salt);
        await User.create({
          name: "System Administrator",
          email: adminEmail,
          password: hashedPassword,
          role: "admin",
          stream: "Science",
          class: "12",
        });
        console.log(`Created Initial Admin Account: ${adminEmail}`);
      }
    }

    // Seed/Upsert Videos
    console.log(`Seeding ${INITIAL_VIDEOS.length} syllabus video entries...`);
    for (const v of INITIAL_VIDEOS) {
      const ytId = getYTId(v.videoUrl);
      await Video.findOneAndUpdate(
        { chapterId: v.chapterId },
        {
          ...v,
          youtubeId: ytId,
          isAvailable: Boolean(ytId),
        },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }

    console.log("Syllabus videos seeded successfully!");
    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

seedDatabase();
